import {
  CERTIFICATE_CSV_HEADERS,
  type CertificateCsvRow,
  csvRowToRecordPayload,
} from "@/lib/certificate-csv"

export type ImportPreviewRow = {
  id: string
  csvRowNumber: number
  data: CertificateCsvRow
  included: boolean
  issues: string[]
}

function normalizeSerial(serial: string) {
  return serial.trim().toUpperCase()
}

export function getImportRowName(row: CertificateCsvRow) {
  return [row.last_name, row.first_name, row.middle_name, row.suffix]
    .map((part) => part.trim())
    .filter(Boolean)
    .join(" ")
}

export function sortImportRowsAlphabetically(rows: ImportPreviewRow[]) {
  return [...rows].sort((a, b) => {
    const nameA = getImportRowName(a.data).toLowerCase()
    const nameB = getImportRowName(b.data).toLowerCase()
    if (nameA !== nameB) return nameA.localeCompare(nameB)

    const serialA = a.data.serial_number.toLowerCase()
    const serialB = b.data.serial_number.toLowerCase()
    return serialA.localeCompare(serialB)
  })
}

export function filterImportRows(rows: ImportPreviewRow[], query: string) {
  const q = query.trim().toLowerCase()
  if (!q) return rows

  return rows.filter((row) => {
    const haystack = [
      row.data.serial_number,
      getImportRowName(row.data),
      row.data.training,
      row.data.course_code,
      row.issues.join(" "),
      String(row.csvRowNumber),
    ]
      .join(" ")
      .toLowerCase()

    return haystack.includes(q)
  })
}

export function applyAutoGeneratedSerials(
  rows: CertificateCsvRow[],
  autoGenerateSerial: boolean
) {
  return rows.map((row, index) => {
    if (row.serial_number.trim() || !autoGenerateSerial) return { ...row }

    return {
      ...row,
      serial_number: `PSI-IMPORT-${new Date().toISOString().slice(0, 10).replace(/-/g, "")}-${String(index + 1).padStart(5, "0")}`,
    }
  })
}

export function buildImportPreviewRows(
  rows: CertificateCsvRow[],
  existingSerials: Set<string>,
  autoGenerateSerial: boolean
): ImportPreviewRow[] {
  const preparedRows = applyAutoGeneratedSerials(rows, autoGenerateSerial)
  const previewRows: ImportPreviewRow[] = preparedRows.map((data, index) => ({
    id: crypto.randomUUID(),
    csvRowNumber: index + 2,
    data: { ...data },
    included: true,
    issues: [],
  }))

  return analyzeImportPreviewRows(previewRows, existingSerials, { initial: true })
}

export function analyzeImportPreviewRows(
  rows: ImportPreviewRow[],
  existingSerials: Set<string>,
  options?: { initial?: boolean }
): ImportPreviewRow[] {
  const previousById = new Map(rows.map((row) => [row.id, row]))
  const nextRows = rows.map((row) => ({
    ...row,
    data: { ...row.data },
    issues: [] as string[],
  }))

  const serialMap = new Map<string, number[]>()

  nextRows.forEach((row, index) => {
    const serial = normalizeSerial(row.data.serial_number)

    if (!serial) {
      row.issues.push("Missing serial number")
      return
    }

    if (!serialMap.has(serial)) serialMap.set(serial, [])
    serialMap.get(serial)!.push(index)
  })

  for (const [serial, indices] of serialMap.entries()) {
    if (indices.length > 1) {
      const rowNumbers = indices.map((index) => nextRows[index].csvRowNumber).join(", ")
      indices.forEach((index) => {
        nextRows[index].issues.push(`Duplicate serial in CSV (rows ${rowNumbers})`)
      })
    }

    if (existingSerials.has(serial)) {
      indices.forEach((index) => {
        nextRows[index].issues.push("Serial already exists in database")
      })
    }
  }

  return nextRows.map((row) => {
    const previous = previousById.get(row.id)
    const defaultIncluded = row.issues.length === 0

    return {
      ...row,
      included: options?.initial ? defaultIncluded : (previous?.included ?? defaultIncluded),
    }
  })
}

export function updateImportPreviewRow(
  rows: ImportPreviewRow[],
  rowId: string,
  data: CertificateCsvRow,
  existingSerials: Set<string>
) {
  const updated = rows.map((row) =>
    row.id === rowId ? { ...row, data: { ...data } } : row
  )
  return analyzeImportPreviewRows(updated, existingSerials)
}

export function toggleImportRowIncluded(rows: ImportPreviewRow[], rowId: string, included: boolean) {
  return rows.map((row) => (row.id === rowId ? { ...row, included } : row))
}

export function importPreviewRowsToPayloads(rows: ImportPreviewRow[]) {
  return rows
    .filter((row) => row.included && row.issues.length === 0)
    .map((row, index) => {
      const payload = csvRowToRecordPayload(row.data, index, false)
      if (!payload.serial_number) {
        throw new Error(`Row ${row.csvRowNumber} is missing a serial number`)
      }
      if (row.issues.length > 0) {
        throw new Error(`Row ${row.csvRowNumber} still has unresolved issues`)
      }
      return payload
    })
}

export function getImportPreviewSummary(rows: ImportPreviewRow[]) {
  const withIssues = rows.filter((row) => row.issues.length > 0).length
  const selected = rows.filter((row) => row.included).length
  const ready = rows.filter((row) => row.included && row.issues.length === 0).length

  return {
    total: rows.length,
    withIssues,
    selected,
    ready,
  }
}

export { CERTIFICATE_CSV_HEADERS }
